sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "8"
install:
  # Use npm 5.7.x since it has introduced `npm ci`
  - if [[ `npm -v` != 5.7* ]]; then npm install -g npm@'>=5.7.1'; fi
  - npm ci
script:
  - npm run test
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
before_script:
  - npm install -g @angular/cli
stages:
  - lint
  - test
  - integration
jobs:
  include:
    - stage: lint
      script:
        - npm run lint:ci

    - stage: integration
      script:
        - ng build --prod --aot
        - npm run test
